version: "3.9"

services:
  postgres:
    image: postgres:15-alpine
    container_name: sentinelpay-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./seed/init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:7-alpine
    container_name: sentinelpay-redis
    ports:
      - "6379:6379"

  payments-api:
    build: ./services/payments-api
    container_name: sentinelpay-payments
    ports:
      - "18001:8001"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ${AWS_REGION}
      KYC_BUCKET: ${KYC_BUCKET}
      WEBHOOK_TIMEOUT: ${WEBHOOK_TIMEOUT}
      RATELIMIT_STORAGE_URI: ${PAYMENTS_RATELIMIT_STORAGE_URI}
      SECRET_KEY: ${SECRET_KEY}
      ENVIRONMENT: ${ENVIRONMENT}
    depends_on:
      - postgres
      - redis

  kyc-api:
    build: ./services/kyc-api
    container_name: sentinelpay-kyc
    ports:
      - "18002:8002"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      RATELIMIT_STORAGE_URI: ${KYC_RATELIMIT_STORAGE_URI}
      JWT_SECRET: ${JWT_SECRET}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ${AWS_REGION}
      KYC_BUCKET: ${KYC_BUCKET}
      BVN_LOOKUP_URL: ${BVN_LOOKUP_URL}
      ENVIRONMENT: ${ENVIRONMENT}
    depends_on:
      - postgres
      - redis

volumes:
  postgres_data:
